import chromadb
import os
import google.generativeai as genai
from chromadb.utils import embedding_functions

# Define a custom embedding function for Gemini
class GeminiEmbeddingFunction(embedding_functions.EmbeddingFunction):
    def __init__(self, api_key: str, model_name: str):
        genai.configure(api_key=api_key)
        self.model_name = model_name

    def __call__(self, input: embedding_functions.CollectionElement) -> List[List[float]]:
        # Ensure input is a list of strings
        if isinstance(input, str):
            texts = [input]
        elif isinstance(input, list):
            texts = input
        else:
            raise TypeError("Input must be a string or a list of strings.")

        embeddings = []
        for text in texts:
            try:
                response = genai.embed_content(
                    model=self.model_name,
                    content=text,
                    task_type="RETRIEVAL_DOCUMENT"
                )
                embeddings.append(response['embedding'])
            except Exception as e:
                print(f"Error generating Gemini embedding for text '{text[:50]}...': {e}")
                embeddings.append([]) # Return empty embedding on error
        return embeddings


class VectorDBService:
    def __init__(self, db_path: str = "./chroma_db", collection_name: str = "rag_collection"):
        self.client = chromadb.PersistentClient(path=db_path)
        
        # Initialize Gemini Embedding Function
        gemini_api_key = os.getenv("GEMINI_KEY")
        gemini_embedding_model = os.getenv("EMBEDDING_MODEL", "models/embedding-001")
        
        if not gemini_api_key:
            raise ValueError("GEMINI_KEY environment variable not set.")
            
        self.gemini_ef = GeminiEmbeddingFunction(api_key=gemini_api_key, model_name=gemini_embedding_model)

        self.collection = self.client.get_or_create_collection(
            name=collection_name, 
            embedding_function=self.gemini_ef # Use the custom Gemini embedding function
        )

    def add_documents(self, documents: list[dict]):
        """
        Adds documents (chunks) to the ChromaDB collection.
        Documents should be a list of dictionaries, each with 'id', 'content', 'metadata'.
        The embeddings will be generated by the collection's embedding function.
        """
        ids = [doc["id"] for doc in documents]
        metadatas = [doc["metadata"] if "metadata" in doc else {} for doc in documents]
        documents_content = [doc["content"] for doc in documents]

        self.collection.add(
            documents=documents_content,
            metadatas=metadatas,
            ids=ids
        )
        print(f"Added {len(documents)} documents to ChromaDB.")

    def query_documents(self, query_embeddings: list[list[float]], n_results: int = 5) -> list[dict]:
        """
        Queries the ChromaDB collection with given query embeddings.
        Note: If the collection has an embedding function, you can also query with texts.
        """
        results = self.collection.query(
            query_embeddings=query_embeddings,
            n_results=n_results,
            include=['documents', 'metadatas']
        )
        return results

    def query_texts(self, query_texts: list[str], n_results: int = 5) -> list[dict]:
        """
        Queries the ChromaDB collection with given text queries (ChromaDB will embed them using its EF).
        """
        results = self.collection.query(
            query_texts=query_texts,
            n_results=n_results,
            include=['documents', 'metadatas']
        )
        return results

if __name__ == "__main__":
    from dotenv import load_dotenv
    load_dotenv() # Load .env for GEMINI_KEY

    # Example Usage:
    # Make sure to set GEMINI_KEY and EMBEDDING_MODEL environment variables
    # os.environ["GEMINI_KEY"] = "YOUR_GEMINI_API_KEY"
    # os.environ["EMBEDDING_MODEL"] = "models/embedding-001"

    db_service = VectorDBService(db_path="./test_chroma_db_gemini")
    
    # Example of adding documents
    sample_docs = [
        {"id": "doc1_g", "content": "ROS (Robot Operating System) is a flexible framework for writing robot software.", "metadata": {"source": "intro_ros.md"}},
        {"id": "doc2_g", "content": "FastAPI is a modern, fast (high-performance) web framework for building APIs with Python 3.7+.", "metadata": {"source": "intro_fastapi.md"}},
        {"id": "doc3_g", "content": "Gemini is a family of multimodal models developed by Google AI.", "metadata": {"source": "intro_gemini.md"}},
    ]
    db_service.add_documents(sample_docs)

    # Example of querying with text (embeddings generated by ChromaDB's EF)
    query_text = "What is a robot operating system?"
    results = db_service.query_texts(query_texts=[query_text], n_results=1)
    print("\nQuery results for text (Gemini EF):")
    print(results)
    
    # Clean up test db
    try:
        if os.path.exists("./test_chroma_db_gemini"):
            import shutil
            shutil.rmtree("./test_chroma_db_gemini")
            print("Cleaned up test_chroma_db_gemini.")
    except Exception as e:
        print(f"Error cleaning up test db: {e}")